import type { ReactNode } from "react";
import Link from "next/link";
import { buttonClassName } from "@/components/ui/button";
import type {
  OpportunityCandidateRow,
  ProjectOpportunityRow,
} from "@/lib/db/types";
import { formatDateTime } from "@/lib/format";

export function OpportunityDetail({
  opportunity,
  candidate,
  projectId,
  runDate,
}: {
  opportunity: ProjectOpportunityRow;
  candidate: OpportunityCandidateRow | null;
  projectId: string;
  runDate: Date | string | null;
}) {
  return (
    <section className="rounded-lg border border-border bg-surface p-5">
      <div className="mb-3 flex flex-wrap items-start justify-between gap-3">
        <div>
          <h2 className="text-sm font-semibold uppercase">{opportunity.name}</h2>
          <p className="mt-1 text-sm text-muted">{opportunity.description}</p>
        </div>
        <span className="text-xs text-muted">Opportunity</span>
      </div>
      <dl className="min-w-0 divide-y divide-border">
        <MetaRow label="Source">Generated by Intelligence</MetaRow>
        <MetaRow label="Intelligence run">
          {runDate ? (
            <Link
              href={`/projects/${projectId}/intelligence?assessment=${opportunity.assessmentId}`}
              className="hover:underline"
            >
              {formatDateTime(runDate)}
            </Link>
          ) : (
            "—"
          )}
        </MetaRow>
        <MetaRow label="Business context">
          {opportunity.businessArea} · {opportunity.businessProcess} ·{" "}
          {opportunity.recommendedCapability}
        </MetaRow>
        <MetaRow label="Evidence">
          {candidate && candidate.evidence.length > 0 ? (
            <ul className="space-y-1">
              {candidate.evidence.map((entry, index) => (
                <li key={`${entry.citation}-${index}`}>{entry.citation}</li>
              ))}
            </ul>
          ) : (
            "Referenced from the source candidate."
          )}
        </MetaRow>
        <MetaRow label="Potential consumption drivers">
          {candidate?.consumptionDrivers.join(", ") ?? "—"}
        </MetaRow>
        <MetaRow label="Potential value drivers">
          {candidate?.valueDrivers.join(", ") ?? "—"}
        </MetaRow>
        <MetaRow label="Constraints">
          {candidate?.constraints.join(", ") ?? "—"}
        </MetaRow>
        <MetaRow label="Next step">Build Business Case</MetaRow>
      </dl>
      <div className="mt-4 flex justify-end">
        <Link
          href={`/projects/${projectId}/business-case`}
          className={buttonClassName()}
        >
          Build Business Case
        </Link>
      </div>
    </section>
  );
}

function MetaRow({
  label,
  children,
}: {
  label: string;
  children: ReactNode;
}) {
  return (
    <div className="grid grid-cols-[10.5rem_minmax(0,1fr)] items-start gap-4 py-2.5 text-sm">
      <dt className="text-muted">{label}</dt>
      <dd className="min-w-0 break-words">{children}</dd>
    </div>
  );
}
